#!/bin/sh

echo "Running Deployment..."

ln -is ~/dotfiles/.chunkwmrc ~/
ln -is ~/dotfiles/.skhdrc ~/
ln -is ~/dotfiles/.vimrc ~/.vimrc

ln -is ~/dotfiles/zsh/.zshenv ~/
ln -is ~/dotfiles/git/.gitignore_global ~/
ln -is ~/dotfiles/intellij/.ideavimrc ~/
ln -is ~/dotfiles/zsh/.zprofile ~/
ln -is ~/dotfiles/zsh/.zshrc ~/
ln -is ~/dotfiles/zsh/.zshrc_aliases ~/

ln -is ~/dotfiles/karabiner/karabiner.json ~/config/karabiner/karabiner.json

ln -is ~/dotfiles/scripts ~/

echo "Deployment complete!"

