#!/bin/sh

killall polybar

polybar bar1 -c ~/dotfiles/polybar/polybar.conf &
polybar bar2 -c ~/dotfiles/polybar/polybar.conf &
polybar topbar1 -c ~/dotfiles/polybar/polybar.conf &
polybar topbar2 -c ~/dotfiles/polybar/polybar.conf &

