#!/bin/sh

killall polybar

# polybar bar1 -c ~/polybar/polybar.conf &
polybar bar2 -c ~/polybar/polybar.conf &
# polybar topbar1 -c ~/polybar/polybar.conf &
polybar topbar2 -c ~/polybar/polybar.conf &
